export const CATALOG_SERVICE_CONTRACTS = Object.freeze({
  materialService: Object.freeze({
    publicName: 'catalog.materialService',
    purpose: 'Read and manage canonical material records for quoting and production.',
    inputs: Object.freeze(['filters', 'materialPayload']),
    outputs: Object.freeze(['MaterialRecord', 'MaterialList']),
    errors: Object.freeze(['permission_denied', 'validation_error', 'persistence_error']),
    permissions: Object.freeze(['catalog.material.read', 'catalog.material.write']),
  }),
  inkService: Object.freeze({
    publicName: 'catalog.inkService',
    purpose: 'Read and manage ink and print technology cost records.',
    inputs: Object.freeze(['filters', 'inkPayload']),
    outputs: Object.freeze(['InkRecord', 'InkList']),
    errors: Object.freeze(['permission_denied', 'validation_error', 'persistence_error']),
    permissions: Object.freeze(['catalog.material.read', 'catalog.material.write']),
  }),
  combinationService: Object.freeze({
    publicName: 'catalog.combinationService',
    purpose: 'Read and manage material combinations and their component details.',
    inputs: Object.freeze(['filters', 'combinationPayload']),
    outputs: Object.freeze(['CombinationRecord', 'CombinationList']),
    errors: Object.freeze(['permission_denied', 'validation_error', 'persistence_error']),
    permissions: Object.freeze(['catalog.material.read', 'catalog.material.write']),
  }),
  technologyService: Object.freeze({
    publicName: 'catalog.technologyService',
    purpose: 'Read approved print and fabrication technologies.',
    inputs: Object.freeze(['filters']),
    outputs: Object.freeze(['TechnologyRecord', 'TechnologyList']),
    errors: Object.freeze(['permission_denied', 'persistence_error']),
    permissions: Object.freeze(['catalog.material.read']),
  }),
  technicalLibraryService: Object.freeze({
    publicName: 'catalog.technicalLibraryService',
    purpose: 'Expose approved technical library recipes and components.',
    inputs: Object.freeze(['filters', 'libraryPayload']),
    outputs: Object.freeze(['TechnicalLibraryRecord', 'TechnicalLibraryList']),
    errors: Object.freeze(['permission_denied', 'validation_error', 'persistence_error']),
    permissions: Object.freeze(['catalog.material.read', 'catalog.material.write']),
  }),
  costRequestService: Object.freeze({
    publicName: 'catalog.costRequestService',
    purpose: 'Track missing cost requests until validation.',
    inputs: Object.freeze(['missingCostPayload', 'validationPayload']),
    outputs: Object.freeze(['CostRequestRecord', 'CostRequestList']),
    errors: Object.freeze(['permission_denied', 'validation_error', 'persistence_error']),
    permissions: Object.freeze(['catalog.cost.validate']),
  }),
});
