
import{useState}from'react';import{useElan}from'../../core/context/ElanContext.jsx';import CrudTable from'../../components/CrudTable.jsx';import{leerEventosCRM,configurarBridge}from'../../core/bridge/CentralBridge.js';
export function Dashboard(){const s=useElan();return <main><h1>Dashboard ELANVISUAL</h1><div className="kpis">{[['Productos',s.productos.length],['Leads',s.leads.length],['Cotizaciones',s.cotizaciones.length],['Pedidos',s.pedidos.length],['OT',s.ordenes.length],['Pagos pendientes',s.pagos.filter(p=>p.estado==='Pendiente').length]].map(x=><div className="kpi" key={x[0]}><b>{x[1]}</b><span>{x[0]}</span></div>)}</div></main>}
export function Productos(){const{s,productos,remove}= {s:useElan(),...useElan()};return <CrudTable title="Productos" rows={productos} fields={[{key:'categoria',label:'Categoría'},{key:'subcategoria',label:'Subcategoría'},{key:'nombre',label:'Producto'},{key:'tipo',label:'Tipo'},{key:'precioVenta',label:'Precio'}]} onDelete={id=>remove('productos',id)}/>}
export function Categorias(){const{categorias,remove}=useElan();return <CrudTable title="Categorías" rows={categorias} fields={[{key:'nombre',label:'Categoría'},{key:'subcategorias',label:'Subcategorías'},{key:'estado',label:'Estado'}]} onDelete={id=>remove('categorias',id)}/>}
export function Materiales(){const{materiales,remove}=useElan();return <CrudTable title="Materiales / Inventario" rows={materiales} fields={[{key:'nombre',label:'Material'},{key:'unidad',label:'Unidad'},{key:'stock',label:'Stock'},{key:'stockMinimo',label:'Mínimo'},{key:'costo',label:'Costo'},{key:'proveedor',label:'Proveedor'}]} onDelete={id=>remove('materiales',id)}/>}
export function Proveedores(){const{proveedores,remove}=useElan();return <CrudTable title="Proveedores" rows={proveedores} fields={[{key:'nombre',label:'Nombre'},{key:'tipo',label:'Tipo'},{key:'productosAsociados',label:'Productos'},{key:'estado',label:'Estado'}]} onDelete={id=>remove('proveedores',id)}/>}
export function Vendedores(){const{vendedores}=useElan();return <CrudTable title="Vendedores" rows={vendedores} fields={[{key:'nombre',label:'Nombre'},{key:'codigo',label:'Código'},{key:'comision',label:'Comisión %'},{key:'estado',label:'Estado'}]}/>}
export function Leads(){const{leads}=useElan();return <CrudTable title="Leads" rows={leads} fields={[{key:'codigo',label:'Código'},{key:'cliente',label:'Cliente'},{key:'producto',label:'Producto'},{key:'estado',label:'Estado'},{key:'fecha',label:'Fecha'}]}/>}
export function Cotizaciones(){const{cotizaciones}=useElan();return <CrudTable title="Cotizaciones" rows={cotizaciones} fields={[{key:'codigo',label:'Código'},{key:'cliente',label:'Cliente'},{key:'vendedor',label:'Vendedor'},{key:'total',label:'Total'},{key:'estado',label:'Estado'}]}/>}
export function Pedidos(){const{pedidos}=useElan();return <CrudTable title="Pedidos" rows={pedidos} fields={[{key:'codigo',label:'Código'},{key:'total',label:'Total'},{key:'estado',label:'Estado'},{key:'fecha',label:'Fecha'}]}/>}
export function Pagos(){const{pagos,validarPago}=useElan();return <section className="card"><h2>Validación de pagos</h2>{pagos.map(p=><div className="line" key={p.id}><b>{p.codigo}</b><span>USD {p.monto}</span><span>{p.estado}</span>{p.estado!=='Validado'&&<button onClick={()=>validarPago(p.id)}>Validar y generar OT</button>}</div>)}</section>}
export function Ordenes(){const{ordenes,actualizarEstadoOT,estadosProduccion}=useElan();return <section className="card"><h2>Órdenes de Trabajo</h2>{ordenes.map(o=><div className="line" key={o.id}><b>{o.codigo}</b><span>{o.estado}</span><select value={o.estado} onChange={e=>actualizarEstadoOT(o.id,e.target.value)}>{estadosProduccion.map(s=><option key={s}>{s}</option>)}</select><a href={o.seguimiento}>Seguimiento</a></div>)}</section>}
export function SimpleAdmin({titulo}){return <main><h1>{titulo}</h1><section className="card"><p>Módulo operativo inicial. Listo para conectar formularios avanzados desde administración sin cambiar arquitectura.</p></section></main>}
export function Configuracion(){const{bancos}=useElan();return <CrudTable title="Datos bancarios" rows={bancos} fields={[{key:'banco',label:'Banco'},{key:'titular',label:'Titular'},{key:'numero',label:'Cuenta'},{key:'moneda',label:'Moneda'},{key:'estado',label:'Estado'}]}/>}
export function CRM(){const[modo,setModo]=useState(localStorage.getItem('elanvisual_bridge_mode')||'local');const[endpoint,setEndpoint]=useState(localStorage.getItem('elanvisual_bridge_endpoint')||'');const eventos=leerEventosCRM();return <main><h1>CRM Central Bridge</h1><section className="card form"><select value={modo} onChange={e=>setModo(e.target.value)}><option>local</option><option>api</option></select><input placeholder="Endpoint API futuro" value={endpoint} onChange={e=>setEndpoint(e.target.value)}/><button onClick={()=>configurarBridge({modo,endpoint})}>Guardar bridge</button></section><section className="card"><h2>Eventos emitidos</h2>{eventos.map((e,i)=><p key={i}>{e.fecha} · {e.nombre}</p>)}</section></main>}
