/* eslint-disable no-console */

export const config = { api: { bodyParser: { sizeLimit: '25mb' } }, maxDuration: 60 };

const ALLOWED_ORIGINS = new Set(['https://visual.elankav.com','https://connect.elankav.com','http://localhost:5173','http://localhost:3000']);
function isAllowedOrigin(origin=''){if(ALLOWED_ORIGINS.has(origin))return true;try{const url=new URL(origin);return url.protocol==='https:'&&url.hostname.startsWith('elanvisual-platform-')&&url.hostname.endsWith('-elanpetvercelapp.vercel.app')}catch{return false}}
function cors(req,res){const origin=req.headers.origin||'';if(isAllowedOrigin(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization, X-Requested-With, Accept, Origin')}
function getConnectConfig(){const baseUrl=String(process.env.CONNECT_BASE_URL||process.env.ELANKAV_CONNECT_URL||'https://connect.elankav.com').trim().replace(/\/+$/,'');const token=String(process.env.CONNECT_DESIGN_TOKEN||'').trim();if(!token){const error=new Error('CONNECT_DESIGN_TOKEN no configurado en ELANVISUAL');error.code='CONNECT_COPILOT_NOT_CONFIGURED';throw error}return{baseUrl,token}}
function getInternalToken(){return String(process.env.CONNECT_INTERNAL_TOKEN||process.env.CONNECT_INTERNAL_API_TOKEN||process.env.ELANKAV_CONNECT_INTERNAL_TOKEN||process.env.ORCHESTRATOR_INTERNAL_TOKEN||process.env.VQS_API_TOKEN||'').trim()}
function getOrchestratorConfig(){const baseUrl=String(process.env.ORCHESTRATOR_BASE_URL||process.env.ELANKAV_ORCHESTRATOR_URL||'https://orchestrator.elankav.com').trim().replace(/\/+$/,'');const token=String(process.env.ORCHESTRATOR_INTERNAL_TOKEN||process.env.ELANKAV_ORCHESTRATOR_INTERNAL_TOKEN||process.env.VQS_API_TOKEN||process.env.CONNECT_INTERNAL_TOKEN||process.env.CONNECT_INTERNAL_API_TOKEN||process.env.ELANKAV_CONNECT_INTERNAL_TOKEN||'').trim();if(!token){const error=new Error('Token interno no configurado para ELAN Runtime');error.code='ELAN_RUNTIME_NOT_CONFIGURED';throw error}return{baseUrl,token}}
async function callLiveInternal(path,body){const internal=getInternalToken();if(!internal){const error=new Error('Token interno no configurado para ELAN Live');error.code='LIVE_VERIFY_NOT_CONFIGURED';throw error}const{baseUrl}=getConnectConfig();const response=await fetch(`${baseUrl}${path}`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${internal}`,'X-Elankav-Internal-Token':internal,'X-Elankav-Platform':'ELANVISUAL'},body:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!response.ok){const error=new Error(data?.error?.message||'Sesión ELAN Live inválida.');error.code=data?.error?.code||'LIVE_SESSION_INVALID';error.status=response.status;throw error}return data?.data||{}}
async function verifyLiveSession(token){const data=await callLiveInternal('/api/v1/live-access/verify',{token});if(!data?.valid)throw Object.assign(new Error('Sesión ELAN Live inválida.'),{code:'LIVE_SESSION_INVALID',status:401});return data.session}
async function exchangeLiveCode(code){const data=await callLiveInternal('/api/v1/live-access/exchange',{code});if(!data?.token||!data?.session)throw Object.assign(new Error('Enlace ELAN Live inválido.'),{code:'LIVE_CODE_INVALID',status:401});return data}
function capabilityManifest(session){const scopes=Array.isArray(session?.scopes)?session.scopes:[];const all=scopes.includes('*');const has=(scope)=>all||scopes.includes(scope);return{role:session?.role||'unknown',scopes,canUseAssistant:true,canUseVoice:true,canUseCamera:false,canCreateDesign:has('design.create'),canGenerateImage:has('image.create'),canGenerateVideo:has('video.create'),canResearchWeb:has('web.research'),canReadAuthorizedPrices:has('price.authorized.read'),canManageMasterPrices:all,canViewMargins:all}}
function unifiedActor(session={}){const role=String(session.role||'unknown').toLowerCase();const owner=role==='owner'||String(session.authority||'').toLowerCase()==='owner_identity';return{role:owner?'owner':role,actorId:owner?'owner':(session.sub||session.actorId||null),registered:true,platformAllowed:true,platforms:owner?['*']:['ELANVISUAL'],scopes:Array.isArray(session.scopes)?session.scopes:[],authority:owner?'owner_identity':(session.authority||null),phone:session.phone||null,canonicalPhone:session.phone||null}}
async function callElanRuntime(path,body){const{baseUrl,token}=getOrchestratorConfig();const response=await fetch(`${baseUrl}${path}`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${token}`,'X-Elankav-Internal-Token':token,'X-Elankav-Platform':'ELANVISUAL','X-Elankav-Source':'ELAN_LIVE'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({ok:false,error:`ELAN Runtime HTTP ${response.status}`}));if(!response.ok||data?.ok===false){const error=new Error(data?.error||data?.message||'ELAN Runtime no pudo ejecutar la herramienta.');error.code=data?.code||'ELAN_RUNTIME_EXECUTION_FAILED';error.status=response.status;throw error}return data}
async function getUnifiedTools(session){return callElanRuntime('/api/v1/elan-runtime/tools',{actor:unifiedActor(session),channel:'copilot',platform:'ELANVISUAL',memoryLimit:20})}
async function executeLiveTool(session,tool,args={}){const execution=await callElanRuntime('/api/v1/elan-runtime/execute',{actor:unifiedActor(session),channel:'copilot',platform:'ELANVISUAL',tool,arguments:args});return execution.result}
async function persistLiveMemory(session,payload={}){return callElanRuntime('/api/v1/elan-runtime/memory/event',{actor:unifiedActor(session),channel:'copilot',platform:'ELANVISUAL',direction:payload.direction,text:payload.text,messageType:payload.messageType||'audio',externalMessageId:payload.externalMessageId||null,occurredAt:payload.occurredAt||null})}
async function callConnectJson({method='POST',path='',body,source='elan-copilot'}={}){const{baseUrl,token}=getConnectConfig();const response=await fetch(`${baseUrl}${path}`,{method,headers:{'Content-Type':'application/json','X-Elankav-Design-Token':token,'X-Elankav-Copilot-Token':token,'X-Elankav-Platform':'ELANVISUAL','X-Elankav-Source':source},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json().catch(()=>({ok:false,error:`CONNECT HTTP ${response.status}`}));return{status:response.status,data}}

export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();try{
  if(req.method==='GET'){
    const resource=String(req.query?.resource||'');
    if(resource==='design-gallery'){const result=await callConnectJson({method:'GET',path:'/api/v1/design/gallery',source:'design-portal'});return res.status(result.status).json(result.data)}
    if(resource==='video-content'){const id=String(req.query?.id||'').trim();if(!id)return res.status(400).json({ok:false,error:'Falta id de video.'});const{baseUrl,token}=getConnectConfig();const upstream=await fetch(`${baseUrl}/api/v1/copilot/video/${encodeURIComponent(id)}`,{headers:{'X-Elankav-Copilot-Token':token,'X-Elankav-Design-Token':token,'X-Elankav-Platform':'ELANVISUAL','X-Elankav-Source':'elan-copilot'}});if(!upstream.ok)return res.status(upstream.status).json({ok:false,error:'Video no disponible todavía.'});const buffer=Buffer.from(await upstream.arrayBuffer());res.setHeader('Content-Type',upstream.headers.get('content-type')||'video/mp4');res.setHeader('Cache-Control','private, max-age=300');return res.status(200).send(buffer)}
    return res.status(200).json({ok:true,endpoint:'/api/elan-ai',version:'ELAN-UNIFIED-RUNTIME-01',status:'ready',operationsCenter:'ELAN_RUNTIME',authority:'CONNECT',channels:['web','whatsapp','web-live']})
  }
  if(req.method!=='POST')return res.status(405).json({ok:false,error:'Método no permitido.'});
  const payload=req.body||{};const tipo=String(payload.tipo||payload.type||'').trim();
  if(tipo==='live-code-exchange'){const exchanged=await exchangeLiveCode(String(payload.code||''));return res.status(200).json({ok:true,token:exchanged.token,session:exchanged.session,capabilities:capabilityManifest(exchanged.session)})}
  if(tipo==='live-session-verify'){const session=await verifyLiveSession(String(payload.token||''));const runtime=await getUnifiedTools(session);return res.status(200).json({ok:true,session,capabilities:capabilityManifest(session),runtime:{name:runtime.runtime,version:runtime.version,tools:(runtime.tools||[]).map((tool)=>tool.name),memory:runtime.memory||null}})}
  if(tipo==='live-tool'){const session=await verifyLiveSession(String(payload.live_session_token||''));const tool=String(payload.tool||payload.name||'').trim();const args=payload.arguments&&typeof payload.arguments==='object'?payload.arguments:{};const result=await executeLiveTool(session,tool,args);return res.status(200).json({ok:true,tool,result,runtime:'ELAN_UNIFIED_RUNTIME',authority:'CONNECT'})}
  if(tipo==='live-memory-event'){const session=await verifyLiveSession(String(payload.live_session_token||''));const direction=String(payload.direction||'').toLowerCase();if(!['inbound','outbound'].includes(direction))return res.status(400).json({ok:false,error:'direction inválido.',code:'LIVE_MEMORY_DIRECTION_INVALID'});const text=String(payload.text||'').trim();if(!text)return res.status(200).json({ok:true,skipped:true});const memory=await persistLiveMemory(session,{direction,text,messageType:payload.message_type||'audio',externalMessageId:payload.external_message_id||null,occurredAt:payload.occurred_at||null});return res.status(200).json({ok:true,memory:memory.memory||memory,runtime:'ELAN_UNIFIED_RUNTIME',authority:'CONNECT'})}
  let forwarded=payload;
  if(String(payload.canal||'').toLowerCase()==='web-live'){
    const session=await verifyLiveSession(String(payload.live_session_token||''));
    const runtime=await getUnifiedTools(session);
    forwarded={...payload,live_session_token:undefined,capabilities:capabilityManifest(session),runtime_context:{...(payload.runtime_context||{}),runtime:runtime.runtime,runtimeVersion:runtime.version,runtimeTools:runtime.tools||[],runtimeMemory:runtime.memory||null,liveSession:unifiedActor(session)}};
  }
  const designTypes=['design-request','design-request-status','design-request-action'];const path=designTypes.includes(tipo)?'/api/v1/design':'/api/v1/copilot';const result=await callConnectJson({method:'POST',path,body:forwarded,source:designTypes.includes(tipo)?'design-portal':'elan-copilot'});return res.status(result.status).json(result.data)
}catch(error){console.error('ERROR ELANVISUAL runtime proxy:',error);const status=[400,401,403,404].includes(error?.status)?error.status:error?.code==='CONNECT_COPILOT_NOT_CONFIGURED'||error?.code==='LIVE_VERIFY_NOT_CONFIGURED'||error?.code==='ELAN_RUNTIME_NOT_CONFIGURED'?503:502;return res.status(status).json({ok:false,error:error?.message||'No fue posible comunicar ELANVISUAL con ELAN Runtime.',code:error?.code||'ELAN_RUNTIME_PROXY_FAILED'})}}