/* eslint-disable no-console */

export const config = { api: { bodyParser: { sizeLimit: '25mb' } }, maxDuration: 60 };

const ALLOWED_ORIGINS = new Set(['https://visual.elankav.com','https://connect.elankav.com','http://localhost:5173','http://localhost:3000']);
function isAllowedOrigin(origin=''){if(ALLOWED_ORIGINS.has(origin))return true;try{const url=new URL(origin);return url.protocol==='https:'&&url.hostname.startsWith('elanvisual-platform-')&&url.hostname.endsWith('-elanpetvercelapp.vercel.app')}catch{return false}}
function cors(req,res){const origin=req.headers.origin||'';if(isAllowedOrigin(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization, X-Requested-With, Accept, Origin')}
function getConnectConfig(){const baseUrl=String(process.env.CONNECT_BASE_URL||process.env.ELANKAV_CONNECT_URL||'https://connect.elankav.com').trim().replace(/\/+$/,'');const token=String(process.env.CONNECT_DESIGN_TOKEN||'').trim();if(!token){const error=new Error('CONNECT_DESIGN_TOKEN no configurado en ELANVISUAL');error.code='CONNECT_COPILOT_NOT_CONFIGURED';throw error}return{baseUrl,token}}
function getInternalToken(){return String(process.env.CONNECT_INTERNAL_TOKEN||process.env.CONNECT_INTERNAL_API_TOKEN||process.env.ELANKAV_CONNECT_INTERNAL_TOKEN||process.env.ORCHESTRATOR_INTERNAL_TOKEN||process.env.VQS_API_TOKEN||'').trim()}
async function callLiveInternal(path,body){const internal=getInternalToken();if(!internal){const error=new Error('Token interno no configurado para ELAN Live');error.code='LIVE_VERIFY_NOT_CONFIGURED';throw error}const{baseUrl}=getConnectConfig();const response=await fetch(`${baseUrl}${path}`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${internal}`,'X-Elankav-Internal-Token':internal,'X-Elankav-Platform':'ELANVISUAL'},body:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!response.ok){const error=new Error(data?.error?.message||'Sesión ELAN Live inválida.');error.code=data?.error?.code||'LIVE_SESSION_INVALID';error.status=response.status;throw error}return data?.data||{}}
async function verifyLiveSession(token){const data=await callLiveInternal('/api/v1/live-access/verify',{token});if(!data?.valid)throw Object.assign(new Error('Sesión ELAN Live inválida.'),{code:'LIVE_SESSION_INVALID',status:401});return data.session}
async function exchangeLiveCode(code){const data=await callLiveInternal('/api/v1/live-access/exchange',{code});if(!data?.token||!data?.session)throw Object.assign(new Error('Enlace ELAN Live inválido.'),{code:'LIVE_CODE_INVALID',status:401});return data}
function capabilityManifest(session){const scopes=Array.isArray(session?.scopes)?session.scopes:[];const all=scopes.includes('*');const has=(scope)=>all||scopes.includes(scope);return{role:session?.role||'unknown',scopes,canUseAssistant:true,canUseVoice:true,canUseCamera:has('camera.vision'),canCreateDesign:has('design.create'),canGenerateImage:has('image.create'),canGenerateVideo:has('video.create'),canResearchWeb:has('web.research'),canReadAuthorizedPrices:has('price.authorized.read'),canManageMasterPrices:all,canViewMargins:all}}
async function callConnectJson({method='POST',path='',body,source='elan-copilot'}={}){const{baseUrl,token}=getConnectConfig();const response=await fetch(`${baseUrl}${path}`,{method,headers:{'Content-Type':'application/json','X-Elankav-Design-Token':token,'X-Elankav-Copilot-Token':token,'X-Elankav-Platform':'ELANVISUAL','X-Elankav-Source':source},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json().catch(()=>({ok:false,error:`CONNECT HTTP ${response.status}`}));return{status:response.status,data}}

export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();try{
  if(req.method==='GET'){
    const resource=String(req.query?.resource||'');
    if(resource==='design-gallery'){const result=await callConnectJson({method:'GET',path:'/api/v1/design/gallery',source:'design-portal'});return res.status(result.status).json(result.data)}
    if(resource==='video-content'){const id=String(req.query?.id||'').trim();if(!id)return res.status(400).json({ok:false,error:'Falta id de video.'});const{baseUrl,token}=getConnectConfig();const upstream=await fetch(`${baseUrl}/api/v1/copilot/video/${encodeURIComponent(id)}`,{headers:{'X-Elankav-Copilot-Token':token,'X-Elankav-Design-Token':token,'X-Elankav-Platform':'ELANVISUAL','X-Elankav-Source':'elan-copilot'}});if(!upstream.ok)return res.status(upstream.status).json({ok:false,error:'Video no disponible todavía.'});const buffer=Buffer.from(await upstream.arrayBuffer());res.setHeader('Content-Type',upstream.headers.get('content-type')||'video/mp4');res.setHeader('Cache-Control','private, max-age=300');return res.status(200).send(buffer)}
    return res.status(200).json({ok:true,endpoint:'/api/elan-ai',version:'ELAN-COPILOT-CONNECT-LIVE-03',status:'ready',operationsCenter:'CONNECT',channels:['web','whatsapp','web-live']})
  }
  if(req.method!=='POST')return res.status(405).json({ok:false,error:'Método no permitido.'});
  const payload=req.body||{};const tipo=String(payload.tipo||payload.type||'').trim();
  if(tipo==='live-code-exchange'){const exchanged=await exchangeLiveCode(String(payload.code||''));return res.status(200).json({ok:true,token:exchanged.token,session:exchanged.session,capabilities:capabilityManifest(exchanged.session)})}
  if(tipo==='live-session-verify'){const session=await verifyLiveSession(String(payload.token||''));return res.status(200).json({ok:true,session,capabilities:capabilityManifest(session)})}
  let forwarded=payload;
  if(String(payload.canal||'').toLowerCase()==='web-live'){
    const session=await verifyLiveSession(String(payload.live_session_token||''));
    forwarded={...payload,live_session_token:undefined,capabilities:capabilityManifest(session),runtime_context:{...(payload.runtime_context||{}),liveSession:{role:session.role,actorId:session.sub,sellerId:session.sellerId||null,phone:session.phone,scopes:session.scopes,authority:session.authority,expiresAt:new Date(session.exp*1000).toISOString()}}};
  }
  const designTypes=['design-request','design-request-status','design-request-action'];const path=designTypes.includes(tipo)?'/api/v1/design':'/api/v1/copilot';const result=await callConnectJson({method:'POST',path,body:forwarded,source:designTypes.includes(tipo)?'design-portal':'elan-copilot'});return res.status(result.status).json(result.data)
}catch(error){console.error('ERROR proxy ELANVISUAL → CONNECT:',error);const status=error?.status===401||error?.status===403?error.status:error?.code==='CONNECT_COPILOT_NOT_CONFIGURED'||error?.code==='LIVE_VERIFY_NOT_CONFIGURED'?503:502;return res.status(status).json({ok:false,error:error?.message||'No fue posible comunicar ELANVISUAL con CONNECT.',code:error?.code||'CONNECT_COPILOT_PROXY_FAILED'})}}